cmake_minimum_required(VERSION 3.25)
include("${CMAKE_CURRENT_LIST_DIR}/../cmake/DependencyManager.cmake")

# Validate declarations without populating or building dependencies.
function(add_dependency name)
  _deps_parse_source("${name}" ${ARGN})
endfunction()
function(add_header_dependency name)
  _deps_parse_source("${name}" ${ARGN})
endfunction()
function(add_binary_dependency name)
  _deps_parse_binary("${name}" ${ARGN})
endfunction()

if(NOT DEFINED DEPS_MANIFEST)
  set(DEPS_MANIFEST "${CMAKE_CURRENT_LIST_DIR}/../cmake/Dependencies.cmake")
endif()
set(BUILD_TESTING ON)
set(BUILD_BENCHMARKING ON)
set(CPP_TEMPLATE_WITH_GLFW ON)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(CMAKE_SIZEOF_VOID_P 8)
set(MSVC_CXX_ARCHITECTURE_ID x64)
foreach(_platform Windows Linux Darwin)
  set(CMAKE_SYSTEM_NAME "${_platform}")
  set(WIN32 FALSE)
  set(UNIX FALSE)
  set(APPLE FALSE)
  set(MSVC FALSE)
  if(_platform STREQUAL "Windows")
    set(WIN32 TRUE)
    set(MSVC TRUE)
  else()
    set(UNIX TRUE)
    if(_platform STREQUAL "Darwin")
      set(APPLE TRUE)
    endif()
  endif()
  include("${DEPS_MANIFEST}")
endforeach()
message(STATUS "[check_deps] All platform/test/benchmark declarations passed")
